### ISSUE TITLE
Build fails if API keys are missing

### ISSUE THREAD

**Issue by NewstHet** [nash-io/openlimits-java#7]
Maybe it would be nice to add a comment that the build.gradle  file should be appended with APIs keys before executing build command.

**Comment by jankjr** [comment]
@NewstHet I think the build still finishes no?

But I just learned that the correct invocation would be `./gradle assemble`. I'll get the readme updated.

**Comment by NewstHet** [comment]
build still finishes, but libs folder only contains openlimits-java-0.1.jar

**Comment by jankjr** [comment]
@NewstHet I'll get it fixed.

**Comment by jankjr** [comment]
@NewstHet  should be solved now.

Sorry about this, I assumed user would use the prebuilt libraries instead.

**Comment by NewstHet** [comment]
Oh, that's totally fine, Maybe that should also be noted at the readme.
